### PR TITLE
Change version string for TYPO3 dependency

### PR DESCRIPTION
**Pull request by spoonerWeb**
Change TYPO3 version to be usable for 8.7.10 and higher.

### CODE REVIEW

**Comment by Mabahe** [comment]
Hey, thx, did you tested with 8.7.15?

**Comment by spoonerWeb** [comment]
Yes...I want to use it on typo3.org. ;)

**Comment by Mabahe** [comment]
Okaaayyy :-)

**Comment by spoonerWeb** [comment]
Error output from composer:

```
  Problem 1
    - Conclusion: remove typo3/cms v8.7.15
    - Conclusion: don't install typo3/cms v8.7.15
    - mabahe/typo3-core-redirects 8.7.10 requires typo3/cms 8.7.10 -> satisfiable by typo3/cms[8.7.10].
    - mabahe/typo3-core-redirects 8.7.9 requires typo3/cms 8.7.9 -> satisfiable by typo3/cms[v8.7.9].
    - don't install typo3/cms 8.7.10|don't install typo3/cms v8.7.15
    - don't install typo3/cms v8.7.9|don't install typo3/cms v8.7.15
    - Installation request for typo3/cms (locked at v8.7.15, required as ^8.7) -> satisfiable by typo3/cms[v8.7.15].
    - Installation request for mabahe/typo3-core-redirects ^8.7 -> satisfiable by mabahe/typo3-core-redirects[8.7.10, 8.7.9].
```

**Comment by Mabahe** [comment]
jep, sure. you have a 8.7.15 now that will work on future versions till the patches are not compatible anymore.

And thx for the reminder to push some fixes for v9 (2451ff7)

**Pull request merged**
